set -g prefix C-a
unbind C-b
bind C-a send-prefix

# Essential Neovim fixes
set-option -sg escape-time 10
set-option -g focus-events on
set-option -g default-terminal "screen-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'

# Better scrollback
set -g history-limit 50000

# Switching
bind -n S-Left switch-client -p
bind -n S-Right switch-client -n

# Create new session
bind c new-session 

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows when one is closed
set -g renumber-windows on

# Vi mode for copy mode
setw -g mode-keys vi

# Better splits (open in current directory)
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
