[opener]
edit = [
  { run = 'nvim --server "$NVIM" --remote-tab "$@"', block = true, for = "unix" },
  { run = 'nvim "$@"', block = true },                                             # fallback if not inside nvim
]
