wallpaper {
    monitor = DP-1
    path = /home/henri/.wallpapers/abstract-background.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/henri/.wallpapers/abstract-background.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = /home/henri/.wallpapers/abstract-background.jpg
    fit_mode = cover
}
