wallpaper {
    monitor = DP-1
    path = /home/henri/.wallpapers/nordic/wallpapers/ign_furkaPass.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/henri/.wallpapers/nordic/wallpapers/ign_furkaPass.jpg
    fit_mode = cover
}
